stages:
  data_ingestion:
    cmd: python src/poxVisionDetection/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/poxVisionDetection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/poxVisionDataSet

  prepare_base_model:
    cmd: python src/poxVisionDetection/pipeline/stage_02_prepare_base_model.py
    deps: 
      - src/poxVisionDetection/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/poxVisionDetection/pipeline/stage_03_model_training.py
    deps:
      - src/poxVisionDetection/pipeline/stage_03_model_training.py
      - src/poxVisionDetection/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/poxVisionDataSet
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE 
      - EPOCHS
      - BATCH_SIZE 
      - AUGMENTATION 
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/poxVisionDetection/pipeline/stage_04_model_evaluation.py
    deps:
      - src/poxVisionDetection/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/poxVisionDataSet
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - score.json:
        cache: false