AUGMENTATION        : True                      # USING ARTIFICIAL TECHNIQUES TO INCREASE THE SIZE OF THE TRAINING DATA BY ROTATING ETC
IMAGE_SIZE          : [224,224,3]
BATCH_SIZE          : 20
INCLUDE_TOP         : False                     # WE WILL TRAIN RESNET50 AS A FEATURE EXTRACTOR NOT A CLASSIFIER SO THE FULLEY CONNECTED 
                                                # LAYER AT THE TOP WILL NOT BE INCLUDED. 
EPOCHS              : 6
CLASSES             : 2
WEIGHTS             : imagenet                  # THE MODEL HAS BEEN TRAINED ON IMGNET DATA SET, HENCE WE WILL KEEP THE PRE TRAINED WEIGHTS
LEARNING_RATE       : 0.01